DROP TABLE IF  EXISTS USERS_TASKS;
DROP TABLE IF  EXISTS TASKS;
DROP TABLE IF  EXISTS USERS; 


CREATE TABLE USERS(ID bigint auto_increment, NAME VARCHAR(255) null);
INSERT INTO USERS (NAME) VALUES ('Melissa');
INSERT INTO USERS (NAME) VALUES ('Fernando');



 
CREATE TABLE TASKS(ID bigint auto_increment, DESCRIPTION VARCHAR(255) null, PRIORITY bigint null);
INSERT INTO TASKS (DESCRIPTION, PRIORITY) VALUES ('Wake up',1);
INSERT INTO TASKS (DESCRIPTION, PRIORITY) VALUES ('Take a shower',2);


CREATE TABLE USERS_TASKS(ID_USER bigint null, ID_TASK bigint null );
INSERT INTO USERS_TASKS (ID_USER,ID_TASK) VALUES (1,1);
INSERT INTO USERS_TASKS (ID_USER,ID_TASK) VALUES (2,1);

/*
 
CREATE TABLE USERS_TASKS(ID bigint auto_increment, DATE DATE NULL, ID_USER bigint null, ID_TASK bigint null );
INSERT INTO USERS_TASKS (ID_USER,ID_TASK) VALUES (1,1);
INSERT INTO USERS_TASKS (ID_USER,ID_TASK) VALUES (2,1);*/
